name: "Eslint code style analysis"

on:
  push:
    branches: ["main"]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
              node-version: 18
        - run: npm ci
        - run: npm run lint